import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'table-of-contents',
    {
      type: 'category',
      label: 'PART I: Foundations of Physical AI',
      items: [
        { type: 'autogenerated', dirName: 'part-1-foundations' },
      ],
      collapsible: false,
    },
    {
      type: 'category',
      label: 'PART II: The Robotic Nervous System',
      items: [
        { type: 'autogenerated', dirName: 'part-2-nervous-system' },
      ],
    },
    {
      type: 'category',
      label: 'PART III: The Digital Body',
      items: [
        { type: 'autogenerated', dirName: 'part-3-digital-body' },
      ],
    },
    {
      type: 'category',
      label: 'PART IV: The Machine Brain',
      items: [
        { type: 'autogenerated', dirName: 'part-4-machine-brain' },
      ],
    },
    {
      type: 'category',
      label: 'PART V: VLA Intelligence',
      items: [
        { type: 'autogenerated', dirName: 'part-5-vla-intelligence' },
      ],
    },
    {
      type: 'category',
      label: 'PART VI: Capstone',
      items: [
        { type: 'autogenerated', dirName: 'part-6-capstone' },
      ],
    },
  ],
};

export default sidebars;
